export const ExceptionTitleList = {
  Success: "Success",
  ValidationError: "ValidationError",
  InternalServerError: "InternalServerError",
  NotFound: "NotFound",
  UnauthorizedAccess: "UnauthorizedAccess",
  TokenExpired: "TokenExpired",
  TooManyTries: "TooManyTries",
  ServiceUnAvailable: "ServiceUnAvailable",
  ThrottleError: "ThrottleError",
  Forbidden: "Forbidden",
  IncorrectOldPassword: "IncorrectOldPassword",
  UserInactive: "UserInactive",
  BadRequest: "BadRequest",
  InvalidCredentials: "InvalidCredentials",
  InvalidRefreshToken: "InvalidRefreshToken",
  UnsupportedFileType: "UnsupportedFileType",
  OtpRequired: "OtpRequired",
  DeleteDefaultError: "DeleteDefaultError",
  RefreshTokenExpired: "RefreshTokenExpired",
  EmailOrPasswordIncorrect: "EmailOrPasswordIncorrect",
  EmailAlreadyExists: "EmailAlreadyExists",
  CategoryAlreadyExists: "CategoryAlreadyExists",
  CategoryNotFound: "CategoryNotFound",
  InvalidToken: "InvalidToken"
};