export const ExceptionTitleList = {
  NotFound: 'Not Found',
  Forbidden: 'Forbidden',
  Unauthorized: 'Unauthorized',
  IncorrectOldPassword: 'incorrectOldPassword',
  UserInactive: 'userInactive',
  BadRequest: 'badRequest',
  InvalidCredentials: 'invalidCredentials',
  InvalidRefreshToken: 'invalidRefreshToken',
  DeleteDefaultError: 'deleteDefaultError',
  RefreshTokenExpired: 'refreshTokenExpired',
  TooManyTries: 'tooManyTries',
  InternalServerError: 'internalServerError',
  EmailOrPasswordIncorrect: 'EmailOrPasswordIncorrect',
} as const;
